# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

     jobs:
       build:
            runs-on:ubunutu-latest
             steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo "Hello, world!"
      - name: Run another script by p roy
        run : echo "we are building github workflow"; ls
